name: Flutter Code Building


on:
  push:
    branches: [ feature-ci-cd, develop, main ]
  pull_request:
    branches: [ feature-ci-cd, develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - run: flutter create -t app new_project
      - run: cp -r ./lib ./new_project/lib
      - run: cp ./pubspec.yaml ./new_project/pubspec.yaml
      - run: cp -r ./assets ./new_project/assets

      - run: flutter pub get
        working-directory: ./new_project

      - run: flutter build apk --release
        working-directory: ./new_project
