name: Flutter Code Formatting

on:
  push:
    branches: [ feature-ci-cd, develop, main ]
  pull_request:
    branches: [ feature-ci-cd, develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - run: flutter pub get